[build]
  command = "npm --prefix frontend run build && pip install -r backend/requirements.txt"
  publish = "frontend/build"
  functions = "backend/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200