# Generated by Django 5.2.4 on 2025-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade_em_estoque', models.IntegerField(default=0)),
                ('unidade_medida', models.CharField(default='unidade', max_length=50)),
                ('ponto_de_ressuprimento', models.IntegerField(default=0, help_text='Quantidade mínima para alertar a necessidade de compra.')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
