# Generated by Django 5.2.4 on 2025-08-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
